radius: 10

sign-text: "[Silo]"

sign-line: 1

filter-item:
  material: BLACK_STAINED_GLASS_PANE
  name: " "

previous-page-item:
  material: ARROW
  name: "&aPrevious Page"

next-page-item:
  material: ARROW
  name: "&aNext Page"

insert-item:
  material: HOPPER
  name: "&aInsert Item"
